kind = "web"
previewPath = "/"
title = "nopad"
version = "1.0.0"
id = "artifacts/nopad"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23177

[services.development]
run = "pnpm --filter @workspace/nopad run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/nopad", "run", "build" ]
publicDir = "artifacts/nopad/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23177"
BASE_PATH = "/"
